server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
jwt:
  header: Authorization
  secret: mySecret
  expiration: 86400
  tokenHead: Bearer